title: null
name: "Unifying LLMs and KGs for QA: Recent Advances and Opportunities"
author: " Chuangtao Ma, Yongrui Chen, Tianxing Wu, Arijit Khan, Haofen Wang"
theme: minima
header_pages:
  - tutorial-edbt25/index.md
exclude:
  - README.md
description: "EDBT25 LLM-KG4QA Tutorial"
social:
  image: https://machuangtao.github.io/images/edbt25.jpg