title: "Unifying LLMs and KGs for QA: Recent Advances and Opportunities"
author: " Chuangtao Ma, Yongrui Chen, Tianxing Wu, Arijit Khan, Haofen Wang"
theme: minima
show_excerpts: True
header_pages:
  - tutorial-edbt25/index.md
exclude:
  - README.md
description: "Unifying LLMs and KGs for QA: Recent Advances and Opportunities"
url: "https://machuangtao.github.io/LLM-KG4QA/tutorial-edbt25"
baseurl: "/"
                